[variables]
NIXPACKS_JDK_VERSION = "17"

[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = [
  "cd server && chmod +x mvnw && ./mvnw clean package -DskipTests"
]

[start]
cmd = "cd server && java -jar target/*.jar"
